name: CI Workflow for automated testing of the weatherflow project

on:
    push:
        branches: 
            - main
            - development
    pull_request:
        branches:
            - main
            - development

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            DOCKER_BUILDKIT: 1

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              with:
                platforms: linux/arm64

            - name: Configure QEMU
              run: |
                docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

            - name: Build docker image
              run: |
                docker build --platform linux/arm64 -t sensorstorm-host-image .

            - name: Run unit tests for WeatherStation
              run: |
                docker run --rm --platform linux/arm64 sensorstorm-host-image ./build/bin/ws_unit_tests
